name: file_picker_extended
description: File Picker with streamed MD5 calculation
version: 0.0.1
homepage: https://github.com/PROGrand/flutter_file_picker_md5

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.4
  file_picker: ^4.4.0
  crypto: ^3.0.1
  convert: ^3.0.1
  async: ^2.8.2
  flutter_plugin_android_lifecycle: ^2.0.5
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: file_picker_extended
      ios:
        default_package: file_picker_extended
      web:
        pluginClass: FilePickerExtendedWeb
        fileName: web/file_picker_extended_web.dart
      macos:
        default_package: file_picker_extended
      windows:
        default_package: file_picker_extended
      linux:
        default_package: file_picker_extended
