name: file_picker_extended
description: File Picker with streamed MD5 calculation
version: 1.0.3
homepage: https://github.com/PROGrand/flutter_file_picker_md5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.2.0
  file_picker: ^8.1.1
  crypto: ^3.0.1
  convert: ^3.0.1
  async: ^2.8.2
  flutter_plugin_android_lifecycle: ^2.0.5
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: org.mtbo.file_picker_extended
        pluginClass: FilePickerExtendedPlugin
      ios:
        package: org.mtbo.file_picker_extended
        pluginClass: FilePickerExtendedPlugin
      web:
        pluginClass: FilePickerExtendedWeb
        fileName: web/file_picker_extended_web.dart
      macos:
        dartPluginClass: FilePickerExtendedNoweb
      windows:
        dartPluginClass: FilePickerExtendedNoweb
      linux:
        dartPluginClass: FilePickerExtendedNoweb
